### ISSUE TITLE
Allow providers to control the fields in the /FeatureServer/<layer num> response

### ISSUE THREAD

**Issue by jkerr5** [FeatureServer/FeatureServer#11]
Per the ```http://<featureservice-url>/<layerId>``` spec here http://resources.arcgis.com/en/help/arcgis-rest-api/#/Layer/02r3000000w6000000/, there are many properties that can be returned to describe each layer. Some of these would be dictated by the features that koop supports but many of them are really the responsibility of the provider to specify them.

For example, ```timeInfo``` and ```relationships``` should be able to be specified via the provider.

At a minimum, can you specify which of the properties the provider can control and what metadata property to use to set them?

**Comment by jkerr5** [comment]
I can create issues for each individual property if you would like but here are a few key ones that don't appear to be able to be set via the provider right now:
1) displayField
1) objectIdField
1) maxRecordCount
1) timeInfo

**Comment by dmfenton** [comment]
all are possible as of 2.2.0

metadata.displayField
metadata.idField
metadata.maxRecordCount
metadata.timeInfo
