### ISSUE TITLE
Query with OutStatistics - No results returned

### ISSUE THREAD

**Issue by apfister** [FeatureServer/FeatureServer#24]
Using Koop 3.5.1

Request: https://koop-three.herokuapp.com/chicagoFood/FeatureServer/0/query?f=json&where=&returnGeometry=false&spatialRel=esriSpatialRelIntersects&outFields=*&groupByFieldsForStatistics=risk&outStatistics=%5B%7B%22statisticType%22%3A%22count%22%2C%22onStatisticField%22%3A%22risk%22%2C%22outStatisticFieldName%22%3A%22countOFrisk%22%7D%5D&outSR=102100

The call doesn't fail, but there are no results returned. There should be multiple categories that come back such has "Risk 1 (High)" and "Risk 3 (Low)". Noticed this when trying to bring in this Koop URL to the web map viewer and symbolize by the "risk" column.

Source GeoJSON @ https://data.cityofchicago.org/resource/cwig-ma7x.geojson

Some sample results for this column come back in a simple query: https://koop-three.herokuapp.com/chicagoFood/FeatureServer/0/query?where=1=1&outFields=risk

**Comment by tomtom92** [comment]
@apfister the issue should be fixed with the most recent version of winnow. Try updating to FeatureServer 2.3.6 and Winnow 1.10.4.

**Comment by tomtom92** [comment]
@apfister, unless there are any other problems, I'll close this issue
