### ISSUE TITLE
Empty URL parameters result in 0 value in provider parameters

### ISSUE THREAD

**Issue by jkerr5** [FeatureServer/FeatureServer#27]
Is it expected behavior for koop to turn empty parameters into 0 in the params passed to the provider? E.g., the following URL:
```
GDeltGKG/FeatureServer/3/query?f=json&orderByFields=
```
results in the following JSON params passed to the provider:
```js
params: { id: GDeltGKG, layer: 3, method: query }, query: { f: json, orderByFields: 0 } }
```

Note that `orderByFields` is the number 0.

**Comment by dmfenton** [comment]
That's odd. I wonder if that's something Express is doing.

**Comment by dmfenton** [comment]
We're unable to repro this one. I suspect this is happening inside your provider.

**Comment by dmfenton** [comment]
Closing this issue since it cannot be reproduced.
